- name: "Copy required for app stack objs"
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../files/{{ item }}"
    dest: "{{ INSTALL_DIR }}"
    mode: "0644"
  run_once: true
  with_items:
    - "{{ SESSIONS_DIR }}"
    - "{{ KEYS_DIR }}"

- name: "Template files"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ INSTALL_DIR }}/{{ item }}"
    mode: "0644"
  loop:
    - "3d-stack.yml"
    - "config.template.json"
  run_once: true

- name: "Deploy app stack from a compose file"
  docker_stack:
    state: present
    name: 3d-app
    with_registry_auth: true
    compose:
      - "{{ INSTALL_DIR }}/3d-stack.yml"
  run_once: true

