- name: "Create deploy dirs"  # todo - move to common
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0644"
  run_once: true # you can change with condition inventory_hostname  == groups['market'][0]
  with_items:
    - "{{ INSTALL_DIR }}"