- name: Log into registry and force re-authorization
  docker_login:
    registry: "{{ DOCKER_REGISTRY_HOST }}"
    username: "{{ DOCKER_REG_USERNAME }}"
    password: "{{ DOCKER_REG_PASSWORD }}"
    reauthorize: yes