- name: "Create default swarm network"
  community.docker.docker_network:
    name: "{{ SWARM_NETWORK_NAME }}"
    attachable: false
    driver: overlay
    internal: no
    state: present
    driver_options:
      encrypted: ""
  when: RECREATE_STACK | default(false)
  run_once: true

  