- hosts: market
  any_errors_fatal: true
  become: true
  gather_facts: true

  roles:
    - role: docker
  tags: docker

- hosts: market
  any_errors_fatal: true
  become: true
  gather_facts: true

  roles:
    - role: caddy_stack
  tags: caddy

- hosts: market
  any_errors_fatal: true
  become: true
  gather_facts: true

  roles:
    - role: db_stack
  tags: db

- hosts: market
  any_errors_fatal: true
  become: true
  gather_facts: true

  roles:
    - role: s3_stack
  tags: s3

- hosts: market
  any_errors_fatal: true
  become: true
  gather_facts: true

  roles:
    - role: market_stack
  tags: market


# - hosts: all
#   tasks:
#     - debug:
#         var: INSTALL_DIR

